name: Scheduled Recording
on:
  workflow_dispatch:
  push:
jobs:
  scehduled-recording:
    permissions:
      tokens: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WIP }}
          service_account: ${{ secrets.UPLOAD_SA }}
